language: scala

scala:
   - 2.11.5

jdk:
   - oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts .travis.jvmopts compile 

   # Tricks to avoid unnecessary cache updates
   - find $HOME/.sbt -name "*.lock" | xargs rm
   - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
   - du -hs $HOME/.*
   - du -hs $HOME/*

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

sudo: false
 
