#
# .travis.yml
#

sudo: false

language: scala

scala:
  - 2.11.6

jdk:
  - oraclejdk8
  - oraclejdk7

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.mvn/repository
    - $HOME/.m2/repository
    - $HOME/.sbt/boot
 
notifications:
  email: false

script:
  # Build routines
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xss8m package test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# eof

